#!/usr/bin/env python3
"""Validate bundled language-pack manifest and launcher payloads."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import platform
import re
import subprocess
import sys
from pathlib import Path
from typing import Iterable


PINNED_VERSION_RE = re.compile(r"^[0-9A-Za-z][0-9A-Za-z._-]*$")

EXPECTED_PAYLOAD = {
    "windows": {
        "rust-analyzer": "language-packs/windows/rust-analyzer/bin/rust-analyzer.exe",
        "clangd": "language-packs/windows/clangd/bin/clangd.exe",
        "typescript-language-server": "language-packs/windows/typescript-language-server/node/typescript-language-server.cmd",
        "pyright": "language-packs/windows/pyright/node/pyright-langserver.cmd",
        "json-language-server": "language-packs/windows/json-language-server/node/vscode-json-language-server.cmd",
        "yaml-language-server": "language-packs/windows/yaml-language-server/node/yaml-language-server.cmd",
        "taplo": "language-packs/windows/taplo/bin/taplo.exe",
        "marksman": "language-packs/windows/marksman/bin/marksman.exe",
        "powershell-editor-services": "language-packs/windows/powershell-editor-services/bin/Start-EditorServices.ps1",
        "cmake-language-server": "language-packs/windows/cmake-language-server/python/Scripts/cmake-language-server.exe",
        "qmlls": "language-packs/windows/qmlls/bin/qmlls.exe",
    },
    "linux": {
        "rust-analyzer": "language-packs/linux/rust-analyzer/bin/rust-analyzer",
        "clangd": "language-packs/linux/clangd/bin/clangd",
        "typescript-language-server": "language-packs/linux/typescript-language-server/node/typescript-language-server",
        "pyright": "language-packs/linux/pyright/node/pyright-langserver",
        "json-language-server": "language-packs/linux/json-language-server/node/vscode-json-language-server",
        "yaml-language-server": "language-packs/linux/yaml-language-server/node/yaml-language-server",
        "taplo": "language-packs/linux/taplo/bin/taplo",
        "marksman": "language-packs/linux/marksman/bin/marksman",
        "powershell-editor-services": "language-packs/linux/powershell-editor-services/bin/Start-EditorServices.sh",
        "cmake-language-server": "language-packs/linux/cmake-language-server/python/bin/cmake-language-server",
        "qmlls": "language-packs/linux/qmlls/bin/qmlls",
    },
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate LocalCodeIDE language-pack manifest.")
    parser.add_argument(
        "--manifest",
        default="resources/language-packs/manifest.json",
        help="Path to language-pack manifest JSON.",
    )
    parser.add_argument(
        "--root",
        default=".",
        help="Repository root used to resolve source paths.",
    )
    parser.add_argument(
        "--runtime-root",
        default="",
        help="Optional runtime directory (for packaged artifact validation).",
    )
    parser.add_argument(
        "--platform",
        choices=["all", "windows", "linux"],
        default="all",
        help="Target platform set to validate.",
    )
    parser.add_argument(
        "--smoke-check",
        action="store_true",
        help="Run launch smoke-checks for launcher scripts available on this host OS.",
    )
    parser.add_argument(
        "--verify-payload",
        action="store_true",
        help="Require expected bundled payload binaries/scripts to exist for each pack.",
    )
    parser.add_argument(
        "--lock-file",
        default="resources/language-packs/checksums.lock.json",
        help="Checksum lock file generated by fetch-language-packs.py.",
    )
    return parser.parse_args()


def fail(message: str) -> None:
    raise ValueError(message)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(1024 * 1024)
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()


def to_path(base: Path, value: str) -> Path:
    return (base / Path(value.replace("\\", "/"))).resolve()


def is_runnable_on_host(target_platform: str) -> bool:
    host = platform.system().lower()
    if target_platform == "windows":
        return host.startswith("win")
    if target_platform == "linux":
        return host == "linux"
    return False


def smoke_check_launcher(launcher: Path, target_platform: str) -> None:
    env = os.environ.copy()
    env["LOCALCODEIDE_LSP_SMOKE_CHECK"] = "1"

    if target_platform == "windows":
        result = subprocess.run(
            [str(launcher), "--help"],
            env=env,
            capture_output=True,
            text=True,
            timeout=10,
            shell=False,
        )
    else:
        result = subprocess.run(
            ["sh", str(launcher), "--help"],
            env=env,
            capture_output=True,
            text=True,
            timeout=10,
            shell=False,
        )

    if result.returncode != 0:
        output = (result.stdout + "\n" + result.stderr).strip()
        fail(f"Launcher smoke-check failed for '{launcher}': {output}")


def iter_platforms(selection: str) -> Iterable[str]:
    if selection == "all":
        return ("windows", "linux")
    return (selection,)


def validate_manifest(
    manifest_path: Path,
    source_root: Path,
    runtime_root: Path | None,
    platform_selection: str,
    smoke_check: bool,
    verify_payload: bool,
    lock_data: dict | None,
) -> None:
    if not manifest_path.exists():
        fail(f"Manifest file not found: {manifest_path}")

    doc = json.loads(manifest_path.read_text(encoding="utf-8"))
    if not isinstance(doc, dict):
        fail("Manifest root must be a JSON object.")

    schema_version = doc.get("schemaVersion")
    if not isinstance(schema_version, int) or schema_version < 2:
        fail("Manifest schemaVersion must be an integer >= 2.")

    packs = doc.get("packs")
    if not isinstance(packs, list) or not packs:
        fail("Manifest must contain a non-empty 'packs' array.")

    seen_ids: set[str] = set()

    for index, pack in enumerate(packs):
        if not isinstance(pack, dict):
            fail(f"packs[{index}] must be an object.")

        pack_id = pack.get("id")
        if not isinstance(pack_id, str) or not pack_id.strip():
            fail(f"packs[{index}].id must be a non-empty string.")
        if pack_id in seen_ids:
            fail(f"Duplicate pack id found: {pack_id}")
        seen_ids.add(pack_id)

        version = pack.get("version")
        if not isinstance(version, str) or not PINNED_VERSION_RE.match(version):
            fail(f"Pack '{pack_id}' has invalid pinned version '{version}'.")
        if version.lower() in {"latest", "nightly", "main"}:
            fail(f"Pack '{pack_id}' version must be pinned, not '{version}'.")

        languages = pack.get("languages")
        if not isinstance(languages, list) or not languages:
            fail(f"Pack '{pack_id}' must provide at least one language.")
        for language in languages:
            if not isinstance(language, str) or not language.strip():
                fail(f"Pack '{pack_id}' contains an invalid language id entry.")

        bundled = pack.get("bundled")
        if not isinstance(bundled, dict):
            fail(f"Pack '{pack_id}' must include a bundled object.")

        args = pack.get("args")
        if not isinstance(args, list):
            fail(f"Pack '{pack_id}' args field must be an array.")

        for target_platform in iter_platforms(platform_selection):
            relative_path = bundled.get(target_platform)
            if not isinstance(relative_path, str) or not relative_path.strip():
                fail(f"Pack '{pack_id}' is missing bundled.{target_platform}.")

            resolution_root = runtime_root if runtime_root is not None else source_root
            launcher = to_path(resolution_root, relative_path)
            if not launcher.exists():
                fail(
                    f"Pack '{pack_id}' launcher missing for {target_platform}: "
                    f"{relative_path} (resolved to {launcher})"
                )
            if not launcher.is_file():
                fail(f"Pack '{pack_id}' launcher is not a file: {launcher}")

            if smoke_check and is_runnable_on_host(target_platform):
                smoke_check_launcher(launcher, target_platform)

            if verify_payload:
                payload_map = EXPECTED_PAYLOAD.get(target_platform, {})
                expected_relpath = payload_map.get(pack_id)
                if expected_relpath:
                    payload_path = to_path(resolution_root, expected_relpath)
                    if not payload_path.exists():
                        fail(
                            f"Pack '{pack_id}' missing expected payload for {target_platform}: "
                            f"{expected_relpath} (resolved to {payload_path})"
                        )
                    if lock_data:
                        prefix = f"language-packs/{target_platform}/{pack_id}/"
                        payload_suffix = expected_relpath[len(prefix):] if expected_relpath.startswith(prefix) else expected_relpath
                        key = f"{pack_id}:{payload_suffix}"
                        expected_hash = (
                            lock_data.get("checksums", {})
                            .get(target_platform, {})
                            .get(key)
                        )
                        if expected_hash:
                            actual_hash = sha256_file(payload_path)
                            if actual_hash.lower() != expected_hash.lower():
                                fail(
                                    f"Checksum mismatch for {target_platform}/{key}: "
                                    f"expected {expected_hash}, got {actual_hash}"
                                )


def main() -> int:
    args = parse_args()
    source_root = Path(args.root).resolve()
    manifest_path = to_path(source_root, args.manifest)
    runtime_root = to_path(source_root, args.runtime_root) if args.runtime_root else None
    lock_path = to_path(source_root, args.lock_file)
    lock_data = None
    if lock_path.exists():
        lock_data = json.loads(lock_path.read_text(encoding="utf-8"))

    try:
        validate_manifest(
            manifest_path=manifest_path,
            source_root=source_root,
            runtime_root=runtime_root,
            platform_selection=args.platform,
            smoke_check=args.smoke_check,
            verify_payload=args.verify_payload,
            lock_data=lock_data,
        )
    except Exception as exc:  # pylint: disable=broad-except
        print(f"[language-packs] validation failed: {exc}")
        return 1

    mode = "runtime artifact" if runtime_root is not None else "source tree"
    print(
        "[language-packs] validation passed "
        f"({mode}; platforms={args.platform}; smoke_check={args.smoke_check}; verify_payload={args.verify_payload})."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
